title: Ping Political
email: hello.the.free.world@gmail.com
description: The official homepage of Ping Political.
baseurl: ''
url: ''
twitter_username: PingPolitical
github_username: hello-free-world
theme: minima
plugins:
  - jekyll-feed
